version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/dev.app.prenostik.com/
hooks:
  BeforeInstall:
    - location: scripts/before-deploy.sh
      runas: root
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 3600
      runas: root